# Generated by Django 4.0.4 on 2022-05-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=200, unique=True), max_length=200, null=True, unique=True),
        ),
    ]
